Error fixing
NoMethodError (undefined method `update_attributes' for #<TodoItem id: 1, description: "This is the first item", completed: false, completed_at: "2022-01-21 10:27:00.000000000 +0000", todo_list_id: 1, created_at: "2022-01-21 10:27:47.670499000 +0000", updated_at: "2022-01-21 10:27:47.670499000 +0000">                                          Did you mean?  update_attribute):                                                                                                                                           app/controllers/todo_items_controller.rb:36:in `update'

But somehow correcting this causes another error?
ArgumentError (wrong number of arguments (given 1, expected 2)):                                                                                                            app/controllers/todo_items_controller.rb:36:in `update'